### ISSUE TITLE
AttributeError: 'Role' object has no attribute 'decorators' Error: Compilation failed

### ISSUE THREAD

**Issue by tekumara** [fizzbee-io/fizzbee#143]
Given:
```
Status = enum('INIT', 'DONE')

role Node:

  action Init:
    self.status = Status.INIT

  action Done:
    self.status = Status.DONE

action Init:
  n = Node()
```

will error with:
```
Traceback (most recent call last):
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/_main/parser/main.py", line 151, in <module>
    main(sys.argv)
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/_main/parser/main.py", line 96, in main
    answer = BuildAstVisitor(stream, file_path=filename).visit(tree)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/rules_python++pip+pypi_312_antlr4_python3_runtime/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/_main/parser/FizzParser.py", line 769, in accept
    return visitor.visitRoot(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/_main/parser/BuildAstVisitor.py", line 29, in visitRoot
    return self.visitFile_input(ctx.getChild(0))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/_main/parser/BuildAstVisitor.py", line 44, in visitFile_input
    childProto = self.visit(child)
                 ^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/rules_python++pip+pypi_312_antlr4_python3_runtime/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/_main/parser/FizzParser.py", line 1063, in accept
    return visitor.visitStmt(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/_main/parser/BuildAstVisitor.py", line 772, in visitStmt
    childProto = self.visit(childStmt)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/rules_python++pip+pypi_312_antlr4_python3_runtime/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/_main/parser/FizzParser.py", line 1401, in accept
    return visitor.visitRole_def_stmt(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tekumara/code3/fizzbee/bazel-bin/parser/parser_bin.runfiles/_main/parser/BuildAstVisitor.py", line 147, in visitRole_def_stmt
    role.decorators.extend(decorators)
    ^^^^^^^^^^^^^^^
AttributeError: 'Role' object has no attribute 'decorators'
Error: Compilation failed
```

Is there any doco on the new syntax for `role`?

Introduced in #138

**Comment by tekumara** [comment]
Fixed by rebuilding the parser:
```
bazel build parser/parser_bin
```
